# Generated by Django 4.2 on 2023-04-26 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('aisistant', '0002_remove_user_email_remove_user_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtended',
            fields=[
                ('documents', models.TextField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
