# Generated by Django 4.1.1 on 2023-05-16 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aisistant', '0004_remove_userextended_documents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextended',
            name='tasks',
        ),
        migrations.CreateModel(
            name='WorkSpace',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('users', models.ManyToManyField(related_name='workspaces', to='aisistant.userextended')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aisistant.workspace'),
        ),
    ]
