# Generated by Django 4.1.1 on 2023-05-16 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aisistant', '0005_remove_userextended_tasks_workspace_task_workspace'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='owner',
            new_name='assigned',
        ),
    ]
