# Generated by Django 4.1.1 on 2023-05-16 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aisistant', '0006_rename_owner_task_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aisistant.userextended'),
        ),
    ]
