# Generated by Django 4.1.1 on 2023-05-16 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aisistant', '0008_alter_task_assigned_alter_task_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='name',
            field=models.TextField(default='My Workspace'),
        ),
        migrations.AlterField(
            model_name='task',
            name='stage',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Heading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headings', to='aisistant.workspace')),
            ],
        ),
    ]
