# Generated by Django 4.1.1 on 2023-05-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aisistant', '0009_task_deadline_workspace_name_alter_task_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
