# Generated by Django 4.1.1 on 2023-05-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aisistant', '0010_alter_workspace_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='todo',
            field=models.TextField(null=True),
        ),
    ]
