# Generated by Django 4.1.1 on 2023-05-16 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aisistant', '0011_task_title_alter_task_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='heading',
            name='order',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='heading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aisistant.heading'),
        ),
    ]
