# Generated by Django 4.1.1 on 2023-05-16 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aisistant', '0012_heading_order_task_heading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='stage',
        ),
    ]
