# Generated by Django 4.1.5 on 2023-05-17 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aisistant", "0014_alter_task_deadline"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="id",
            new_name="task_id",
        ),
    ]
